import sys
import json
import os
from datetime import datetime


def extract_log_lines(content: str):
    lines = content.splitlines()
    in_logs = False
    logs = []

    for line in lines:
        stripped = line.strip()
        if stripped.lower() == "## logs":
            in_logs = True
            continue
        if in_logs and stripped.startswith("## "):
            break
        if in_logs and stripped.startswith("- "):
            logs.append(stripped[2:].strip())

    return logs


def capture_experience(content, source_file, status, loop_count, knowledge_dir, experience_file, seen_file):
    if not content:
        return

    logs = extract_log_lines(content)
    if not logs:
        return

    os.makedirs(knowledge_dir, exist_ok=True)

    seen = set()
    if os.path.exists(seen_file):
        try:
            with open(seen_file, "r", encoding="utf-8") as f:
                data = json.load(f)
            seen = set(data.get("seen_logs", []))
        except Exception:
            seen = set()

    new_logs = [line for line in logs if line not in seen]
    if not new_logs:
        return

    first_write = not os.path.exists(experience_file)
    with open(experience_file, "a", encoding="utf-8") as f:
        if first_write:
            f.write("# Debug and Development Experience\n\n")
            f.write("This file is auto-generated by `.cursor/scripts/stop_hook.py`.\n\n")

        ts = datetime.utcnow().strftime("%Y-%m-%d %H:%M:%S UTC")
        f.write(f"## {ts}\n")
        f.write(f"- source: `{source_file or 'unknown'}`\n")
        f.write(f"- status: `{status}`\n")
        f.write(f"- loop_count: `{loop_count}`\n")
        for log in new_logs:
            f.write(f"- lesson: {log}\n")
        f.write("\n")

    seen.update(new_logs)
    with open(seen_file, "w", encoding="utf-8") as f:
        json.dump({"seen_logs": sorted(seen)}, f, ensure_ascii=True, indent=2)


def main():
    try:
        input_data = json.load(sys.stdin)
    except Exception:
        input_data = {}

    status = input_data.get("status", "completed")
    loop_count = input_data.get("loop_count", 0)

    state_file = "workflow_state.md"
    scratchpad_file = ".cursor/scratchpad.md"

    knowledge_dir = ".cursor/knowledge"
    experience_file = os.path.join(knowledge_dir, "debug_dev_experience.md")
    seen_file = os.path.join(knowledge_dir, ".experience_seen.json")

    content = ""
    source_file = None
    if os.path.exists(state_file):
        with open(state_file, "r", encoding="utf-8") as f:
            content = f.read()
        source_file = state_file
    elif os.path.exists(scratchpad_file):
        with open(scratchpad_file, "r", encoding="utf-8") as f:
            content = f.read()
        source_file = scratchpad_file

    capture_experience(
        content=content,
        source_file=source_file,
        status=status,
        loop_count=loop_count,
        knowledge_dir=knowledge_dir,
        experience_file=experience_file,
        seen_file=seen_file,
    )

    if "DONE" in content:
        print(json.dumps({}))
        return

    followup = {
        "followup_message": (
            f"Please continue the task. Current loop count: {loop_count}. "
            "Check workflow_state.md for the next step."
        )
    }
    print(json.dumps(followup))


if __name__ == "__main__":
    main()
